### ISSUE TITLE
add predict_obs_cov to dual_lofi

### ISSUE THREAD

**Issue by murphyk** [probml/rebayes#15]
Copy https://github.com/probml/rebayes/blob/main/rebayes/low_rank_filter/lofi.py#L174 to dual_lofi

**Comment by petergchang** [comment]
Already exists in
https://github.com/probml/rebayes/blob/ca72fbb91e92dcbb61b4abe44c1092df0bd07371/rebayes/low_rank_filter/dual_lofi.py#L188
