### ISSUE TITLE
create `pred_obs_mc` method

### ISSUE THREAD

**Issue by murphyk** [probml/rebayes#16]
- create `pred_obs_mc` method for all the estimators that samples from bel(theta), using the full cov or DLR approximation, and then returns a S*N*C matrix  of predictions on the N test points. Similar to ` xmap_yhat_sample` and ` xmap_yhat_sample_lofi_dlr`, but methods of the estimator class, not buried inside a notebook.

**Comment by murphyk** [comment]
For the 1d regression demos,
- change  xmap_yhat_sample_lofi_lin in demos/nonstat-1d-regression to use the predict_obs_cov method.
- For the linear plugin approximation , plot +- confidence intervals on each predicted output, rather than drawing independent samples from the marginals p(y_t|x_t; mu_{t|t-1})..

**Comment by gerdm** [comment]
See 
* bf332de3662eb9620912f6e74049990025c54680
* d02c71c0f6a3ed6c1b46d8bc1e1050551c8b7f8c
