### ISSUE TITLE
viking

### ISSUE THREAD

**Issue by murphyk** [probml/rebayes#36]
The goal is to reimplement and extend the viking algorithm described below

J. de Vilmarest and O. Wintenberger, “Viking: Variational Bayesian Variance Tracking,” arXiv [cs.LG], Apr. 16, 2021 [Online]. Available: http://arxiv.org/abs/2104.10777
https://gitlab.com/JosephdeVilmarest/state-space-post-covid-forecasting/-/blob/main/R/viking.R

Steps:

1.  Generalize the math to work for EKF case (full covariance posterior for mu, P)
2. Implement viking+EKF, extending the above R code from the linear regression setting to nonlinear obs model
3. Generalize the math to work for LoFi case (should be an easy extension, since we just need to replace sigma^2 with E[sigma^2] and Q with E[Q] in the lofi step)
4. Implement viking+lofi

**Comment by murphyk** [comment]
J. De Vilmarest, Y. Goude, and O. Wintenberger, “VIKING: Variational Bayesian variance tracking winning a post-covid day-ahead electricity load forecasting competition.” [Online]. Available: http://roseyu.com/time-series-workshop/submissions/2021/TSW-ICML2021_paper_15.pdf. [Accessed: Apr. 06, 2023]

**Comment by petergchang** [comment]
J. De Vilmarest and Y. Goude, "State-Space Models for Online Post-Covid Electricity Load Forecasting Competition," in IEEE Open Access Journal of Power and Energy, vol. 9, pp. 192-201, 2022, doi: 10.1109/OAJPE.2022.3141883.
https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=9677626
