### ISSUE TITLE
GGT

### ISSUE THREAD

**Issue by murphyk** [probml/rebayes#9]

**Comment by murphyk** [comment]
https://github.com/tensorflow/tensorflow/blob/v1.13.2/tensorflow/contrib/opt/python/training/ggt.py

N. Agarwal et al., “Efficient Full-Matrix Adaptive Regularization,” in ICML, 09--15 Jun 2019, vol. 97, pp. 102–110 [Online]. Available: http://proceedings.mlr.press/v97/agarwal19b.html

**Comment by petergchang** [comment]
Closed in 47ee8241951d7feaddb65e3e43e5e2d16b30757f.
